
package com.example.consumingwebservice.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "GemiPort", targetNamespace = "http://tr.gov.sg/ws/gemi")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GemiPort {


    /**
     * 
     * @param getGemiRequest
     * @return
     *     returns com.example.consumingwebservice.wsdl.GetGemiResponse
     */
    @WebMethod
    @WebResult(name = "getGemiResponse", targetNamespace = "http://tr.gov.sg/ws/gemi", partName = "getGemiResponse")
    public GetGemiResponse getGemi(
        @WebParam(name = "getGemiRequest", targetNamespace = "http://tr.gov.sg/ws/gemi", partName = "getGemiRequest")
        GetGemiRequest getGemiRequest);

}
