
package com.example.consumingwebservice.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "GemiPortService", targetNamespace = "http://tr.gov.sg/ws/gemi", wsdlLocation = "http://localhost:8080/ws/gemi.wsdl")
public class GemiPortService
    extends Service
{

    private final static URL GEMIPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException GEMIPORTSERVICE_EXCEPTION;
    private final static QName GEMIPORTSERVICE_QNAME = new QName("http://tr.gov.sg/ws/gemi", "GemiPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/gemi.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GEMIPORTSERVICE_WSDL_LOCATION = url;
        GEMIPORTSERVICE_EXCEPTION = e;
    }

    public GemiPortService() {
        super(__getWsdlLocation(), GEMIPORTSERVICE_QNAME);
    }

    public GemiPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GEMIPORTSERVICE_QNAME, features);
    }

    public GemiPortService(URL wsdlLocation) {
        super(wsdlLocation, GEMIPORTSERVICE_QNAME);
    }

    public GemiPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GEMIPORTSERVICE_QNAME, features);
    }

    public GemiPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GemiPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GemiPort
     */
    @WebEndpoint(name = "GemiPortSoap11")
    public GemiPort getGemiPortSoap11() {
        return super.getPort(new QName("http://tr.gov.sg/ws/gemi", "GemiPortSoap11"), GemiPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GemiPort
     */
    @WebEndpoint(name = "GemiPortSoap11")
    public GemiPort getGemiPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://tr.gov.sg/ws/gemi", "GemiPortSoap11"), GemiPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GEMIPORTSERVICE_EXCEPTION!= null) {
            throw GEMIPORTSERVICE_EXCEPTION;
        }
        return GEMIPORTSERVICE_WSDL_LOCATION;
    }

}
